/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardOwnerRepoRouteImport } from './routes/board.$owner.$repo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BoardOwnerRepoIndexRouteImport } from './routes/board.$owner.$repo.index'
import { Route as BoardOwnerRepoCostRouteImport } from './routes/board.$owner.$repo.cost'
import { Route as BoardOwnerRepoViewRouteImport } from './routes/board.$owner.$repo.$view'

const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardOwnerRepoRoute = BoardOwnerRepoRouteImport.update({
  id: '/board/$owner/$repo',
  path: '/board/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardOwnerRepoIndexRoute = BoardOwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardOwnerRepoRoute,
} as any)
const BoardOwnerRepoCostRoute = BoardOwnerRepoCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => BoardOwnerRepoRoute,
} as any)
const BoardOwnerRepoViewRoute = BoardOwnerRepoViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => BoardOwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/board/$owner/$repo': typeof BoardOwnerRepoRouteWithChildren
  '/board/$owner/$repo/$view': typeof BoardOwnerRepoViewRoute
  '/board/$owner/$repo/cost': typeof BoardOwnerRepoCostRoute
  '/board/$owner/$repo/': typeof BoardOwnerRepoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/board/$owner/$repo/$view': typeof BoardOwnerRepoViewRoute
  '/board/$owner/$repo/cost': typeof BoardOwnerRepoCostRoute
  '/board/$owner/$repo': typeof BoardOwnerRepoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/board/$owner/$repo': typeof BoardOwnerRepoRouteWithChildren
  '/board/$owner/$repo/$view': typeof BoardOwnerRepoViewRoute
  '/board/$owner/$repo/cost': typeof BoardOwnerRepoCostRoute
  '/board/$owner/$repo/': typeof BoardOwnerRepoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/guide'
    | '/api/auth/$'
    | '/board/$owner/$repo'
    | '/board/$owner/$repo/$view'
    | '/board/$owner/$repo/cost'
    | '/board/$owner/$repo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/guide'
    | '/api/auth/$'
    | '/board/$owner/$repo/$view'
    | '/board/$owner/$repo/cost'
    | '/board/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/guide'
    | '/api/auth/$'
    | '/board/$owner/$repo'
    | '/board/$owner/$repo/$view'
    | '/board/$owner/$repo/cost'
    | '/board/$owner/$repo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GuideRoute: typeof GuideRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  BoardOwnerRepoRoute: typeof BoardOwnerRepoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$owner/$repo': {
      id: '/board/$owner/$repo'
      path: '/board/$owner/$repo'
      fullPath: '/board/$owner/$repo'
      preLoaderRoute: typeof BoardOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$owner/$repo/': {
      id: '/board/$owner/$repo/'
      path: '/'
      fullPath: '/board/$owner/$repo/'
      preLoaderRoute: typeof BoardOwnerRepoIndexRouteImport
      parentRoute: typeof BoardOwnerRepoRoute
    }
    '/board/$owner/$repo/cost': {
      id: '/board/$owner/$repo/cost'
      path: '/cost'
      fullPath: '/board/$owner/$repo/cost'
      preLoaderRoute: typeof BoardOwnerRepoCostRouteImport
      parentRoute: typeof BoardOwnerRepoRoute
    }
    '/board/$owner/$repo/$view': {
      id: '/board/$owner/$repo/$view'
      path: '/$view'
      fullPath: '/board/$owner/$repo/$view'
      preLoaderRoute: typeof BoardOwnerRepoViewRouteImport
      parentRoute: typeof BoardOwnerRepoRoute
    }
  }
}

interface BoardOwnerRepoRouteChildren {
  BoardOwnerRepoViewRoute: typeof BoardOwnerRepoViewRoute
  BoardOwnerRepoCostRoute: typeof BoardOwnerRepoCostRoute
  BoardOwnerRepoIndexRoute: typeof BoardOwnerRepoIndexRoute
}

const BoardOwnerRepoRouteChildren: BoardOwnerRepoRouteChildren = {
  BoardOwnerRepoViewRoute: BoardOwnerRepoViewRoute,
  BoardOwnerRepoCostRoute: BoardOwnerRepoCostRoute,
  BoardOwnerRepoIndexRoute: BoardOwnerRepoIndexRoute,
}

const BoardOwnerRepoRouteWithChildren = BoardOwnerRepoRoute._addFileChildren(
  BoardOwnerRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GuideRoute: GuideRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  BoardOwnerRepoRoute: BoardOwnerRepoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
